version: "3"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./mongodb_data:/data/db"
      - "./mongodb_config:/data/configdb"

  backend:
   build:
     context: .
   container_name: backend
   depends_on:
     - mongodb
   ports:
      - 5000:5000
   restart: always
   env_file:
     - ./.env
   logging:
     driver: "json-file"
     options:
       max-size: "200k"
       max-file: "10"
